import { DayItinerary, TransportType } from './types';

/**
 * ITINERARY DATA SOURCE
 *
 * To update the itinerary:
 * 1. Ensure your data matches the DayItinerary interface in types.ts
 * 2. Replace the content of this array.
 * 3. Dates should be in "M/D" format for the Weather Widget to detect automatically.
 */

export const ITINERARY_DATA: DayItinerary[] = [
  {
    isoDate: '2026-08-27',
    date: '8/27（四）',
    dayTitle: 'Day 1',
    theme: '抵達名古屋',
    focus: '中部國際機場入境、前往伏見飯店、榮/伏見簡單晚餐',
    items: [
      {
        id: 'd1-1',
        time: '18:45',
        title: '抵達中部國際機場 Centrair',
        description: 'JX 838 抵達名古屋 NGO。入境、領行李後前往名鐵中部國際機場站。',
        address_jp: '愛知県常滑市セントレア1-1',
        address_en: '1-1 Centrair, Tokoname, Aichi',
        coordinates: { lat: 34.8584, lng: 136.8054 },
        transportType: TransportType.FLIGHT,
        transportDetail: 'Starlux Airlines JX 838 TPE → NGO',
        googleMapsQuery: 'Chubu Centrair International Airport',
        recommendedFood: ["機場內輕食","名古屋伴手禮預覽"],
        nearbySpots: ["Flight of Dreams","Sky Deck"],
        shoppingSideQuests: [{"name":"Centrair 4F ちょうちん横丁","category":"餐飲/伴手禮","description":"入境後可先簡單補給，但不建議久留，先進市區較穩。"}],
      },
      {
        id: 'd1-2',
        time: '19:45',
        title: '搭名鐵前往名古屋站',
        description: '從中部國際機場搭名鐵 μ-SKY 或特急到名鐵名古屋站，再轉地下鐵東山線到伏見站。',
        address_jp: '愛知県名古屋市中村区名駅1丁目',
        address_en: 'Meieki 1-chome, Nakamura-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1707, lng: 136.884 },
        transportType: TransportType.TRAIN,
        transportDetail: '名鐵中部國際機場站 → 名鐵名古屋站；轉地下鐵東山線 名古屋站 → 伏見站',
        googleMapsQuery: 'Meitetsu Nagoya Station',
        recommendedFood: ["車站便當","名古屋手羽先"],
        nearbySpots: ["名古屋站","JR Gate Tower","KITTE 名古屋"],
        shoppingSideQuests: [{"name":"JR Gate Tower","category":"百貨/餐廳","description":"若抵達時間較早，可在名古屋站區快速用餐。"}],
      },
      {
        id: 'd1-3',
        time: '20:30',
        title: '入住 Daiwa Roynet Hotel Nagoya Fushimi',
        description: '飯店位於伏見站 6 號出口步行約 2 分鐘，適合作為名古屋市區與犬山一日遊的基地。入住後整理行李。',
        address_jp: '愛知県名古屋市中区栄1丁目5-21',
        address_en: '1-5-21 Sakae, Naka-ku, Nagoya, Aichi',
        coordinates: { lat: 35.16769, lng: 136.89651 },
        transportType: TransportType.WALK,
        transportDetail: '伏見站 6 號出口步行約 2 分鐘前往飯店',
        googleMapsQuery: 'Daiwa Roynet Hotel Nagoya Fushimi',
        recommendedFood: ["便利商店宵夜","伏見居酒屋","手羽先"],
        nearbySpots: ["伏見站","御園座","榮商圈"],
        shoppingSideQuests: [{"name":"伏見周邊便利商店","category":"補給","description":"購買水、早餐、交通 IC 卡儲值用品。"}],
      },
      {
        id: 'd1-4',
        time: '21:00',
        title: '伏見/榮周邊晚餐',
        description: '第一晚不安排重景點，以伏見或榮周邊簡單晚餐為主，避免晚抵達後過度疲勞。',
        address_jp: '愛知県名古屋市中区栄',
        address_en: 'Sakae, Naka-ku, Nagoya',
        coordinates: { lat: 35.1686, lng: 136.9062 },
        transportType: TransportType.WALK,
        transportDetail: '飯店步行或搭地下鐵 1 站至榮站',
        googleMapsQuery: 'Sakae Nagoya',
        recommendedFood: ["世界の山ちゃん手羽先","味噌煮込みうどん","名古屋喫茶店"],
        nearbySpots: ["Oasis 21","久屋大通公園","中部電力 MIRAI TOWER"],
        shoppingSideQuests: [{"name":"榮地下街","category":"地下街/餐飲","description":"晚餐與簡單採買選擇多，雨天也方便。"}],
      },
    ],
  },
  {
    isoDate: '2026-08-28',
    date: '8/28（五）',
    dayTitle: 'Day 2',
    theme: '名古屋城、圓頓寺、榮區 Domatsuri',
    focus: '市中心北側與榮區集中移動，晚上安排 Domatsuri',
    items: [
      {
        id: 'd2-1',
        time: '09:00',
        title: '從飯店出發前往名古屋城',
        description: '由伏見站搭地下鐵至名古屋城站周邊，上午先參觀名古屋城與本丸御殿。',
        address_jp: '愛知県名古屋市中区本丸1-1',
        address_en: '1-1 Honmaru, Naka-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1856, lng: 136.8991 },
        transportType: TransportType.TRAIN,
        transportDetail: '伏見站 → 榮站轉名城線 → 名古屋城站；出站後步行',
        googleMapsQuery: 'Nagoya Castle',
        recommendedFood: ["金シャチ横丁小吃","味噌豬排","名古屋コーチン料理"],
        nearbySpots: ["本丸御殿","金シャチ横丁","二之丸庭園"],
        shoppingSideQuests: [{"name":"金シャチ横丁","category":"餐飲/伴手禮","description":"名古屋城旁的餐飲區，適合午餐或買城郭限定伴手禮。"}],
      },
      {
        id: 'd2-2',
        time: '11:30',
        title: '金シャチ横丁午餐',
        description: '在名古屋城旁用餐，避免中午再跨區移動。可選名古屋名物料理或輕食。',
        address_jp: '愛知県名古屋市中区三の丸1丁目2',
        address_en: '1-2 Sannomaru, Naka-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1845, lng: 136.8948 },
        transportType: TransportType.WALK,
        transportDetail: '名古屋城園區步行前往',
        googleMapsQuery: 'Kinshachi Yokocho Nagoya',
        recommendedFood: ["味噌豬排","名古屋コーチン親子丼","きしめん"],
        nearbySpots: ["名古屋城正門","本丸御殿","愛知縣體育館周邊"],
        shoppingSideQuests: [{"name":"金シャチ横丁 義直ゾーン","category":"餐飲","description":"以名古屋老字號與地方料理為主。"}],
      },
      {
        id: 'd2-3',
        time: '13:00',
        title: '圓頓寺商店街與四間道散策',
        description: '從名古屋城移動到圓頓寺與四間道，逛老商店街、藏屋建築、咖啡與小店。',
        address_jp: '愛知県名古屋市西区那古野1丁目',
        address_en: '1 Nagono, Nishi-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1771, lng: 136.8911 },
        transportType: TransportType.TRAIN,
        transportDetail: '名古屋城周邊 → 丸之內/國際中心周邊；再步行至圓頓寺、四間道',
        googleMapsQuery: 'Endoji Shopping Street Nagoya',
        recommendedFood: ["老街咖啡","喫茶店甜點","炸物小吃"],
        nearbySpots: ["圓頓寺本町商店街","四間道","那古野老街"],
        shoppingSideQuests: [{"name":"圓頓寺商店街","category":"商店街","description":"老店、咖啡店與小型雜貨店集中，適合慢逛。"}],
      },
      {
        id: 'd2-4',
        time: '16:00',
        title: '回飯店休息',
        description: '回榮 1 丁目的 Daiwa Roynet 飯店休息與放戰利品，傍晚再前往榮區看 Domatsuri，避免全天步行過度。',
        address_jp: '愛知県名古屋市中区栄1丁目5-21',
        address_en: '1-5-21 Sakae, Naka-ku, Nagoya, Aichi',
        coordinates: { lat: 35.16769, lng: 136.89651 },
        transportType: TransportType.WALK,
        transportDetail: '圓頓寺/四間道步行或搭短程地下鐵回伏見站，再步行至飯店',
        googleMapsQuery: 'Daiwa Roynet Hotel Nagoya Fushimi',
        recommendedFood: ["便利商店飲料","咖啡","輕食"],
        nearbySpots: ["伏見站","御園座"],
        shoppingSideQuests: [{"name":"伏見地下鐵周邊","category":"補給","description":"回飯店前可補水或買小點心。"}],
      },
      {
        id: 'd2-5',
        time: '17:30',
        title: '榮區與 Oasis 21',
        description: '前往榮區，先逛 Oasis 21、久屋大通公園與電視塔周邊，再銜接 Domatsuri 晚間演舞。',
        address_jp: '愛知県名古屋市東区東桜1丁目11-1',
        address_en: '1-11-1 Higashisakura, Higashi-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1702, lng: 136.9086 },
        transportType: TransportType.TRAIN,
        transportDetail: '伏見站 → 榮站；出站步行至 Oasis 21、久屋大通公園',
        googleMapsQuery: 'Oasis 21 Nagoya',
        recommendedFood: ["榮地下街餐廳","味噌豬排","手羽先"],
        nearbySpots: ["Oasis 21","中部電力 MIRAI TOWER","久屋大通公園"],
        shoppingSideQuests: [{"name":"LACHIC","category":"百貨/餐廳","description":"榮區好用的晚餐與購物備案。"}],
      },
      {
        id: 'd2-6',
        time: '18:30',
        title: 'Domatsuri 2026 夜間演舞',
        description: '安排第28回にっぽんど真ん中祭り。8/28 為開幕日晚間時段，適合排入榮區晚上行程。',
        address_jp: '愛知県名古屋市中区栄3丁目65 久屋大通公園',
        address_en: 'Hisaya Odori Park, Sakae 3-chome, Naka-ku, Nagoya',
        coordinates: { lat: 35.1648, lng: 136.9085 },
        transportType: TransportType.WALK,
        transportDetail: 'Oasis 21 或榮站周邊步行前往久屋大通公園會場',
        googleMapsQuery: 'Hisaya Odori Park Edion Hisaya Plaza',
        recommendedFood: ["祭典攤位小吃","手羽先","味噌豬排"],
        nearbySpots: ["久屋大通公園","榮商圈","矢場町"],
        shoppingSideQuests: [{"name":"名古屋 PARCO","category":"購物/餐廳","description":"若祭典人潮太多，可轉入百貨商場用餐休息。"}],
      },
      {
        id: 'd2-7',
        time: '20:30',
        title: '榮/矢場町晚餐',
        description: '祭典後在榮或矢場町用餐，避免再跨區。建議選矢場とん、世界の山ちゃん或百貨餐廳。',
        address_jp: '愛知県名古屋市中区大須3丁目6-18',
        address_en: '3-6-18 Osu, Naka-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1602, lng: 136.9068 },
        transportType: TransportType.WALK,
        transportDetail: '久屋大通公園步行至矢場町/榮餐廳區',
        googleMapsQuery: 'Yabaton Yabacho Honten',
        recommendedFood: ["矢場とん味噌豬排","世界の山ちゃん手羽先","榮地下街餐廳"],
        nearbySpots: ["矢場町","松坂屋名古屋店","名古屋 PARCO"],
        shoppingSideQuests: [{"name":"松坂屋名古屋店","category":"百貨","description":"晚餐前後可逛地下食品街與百貨。"}],
      },
    ],
  },
  {
    isoDate: '2026-08-29',
    date: '8/29（六）',
    dayTitle: 'Day 3',
    theme: '覺王山商店街與大須商店街',
    focus: '東山線文青街區接大須商店街，下午晚餐不跨遠區',
    items: [
      {
        id: 'd3-1',
        time: '09:30',
        title: '覺王山商店街',
        description: '由伏見站搭東山線至覺王山站，逛參道型商店街、雜貨、甜點與咖啡店。',
        address_jp: '愛知県名古屋市千種区覚王山通',
        address_en: 'Kakuozan-dori, Chikusa-ku, Nagoya, Aichi',
        coordinates: { lat: 35.166, lng: 136.952 },
        transportType: TransportType.TRAIN,
        transportDetail: '伏見站 → 覺王山站，地下鐵東山線直達',
        googleMapsQuery: 'Kakuozan Shopping Street Nagoya',
        recommendedFood: ["覺王山咖啡","和菓子","甜點","手作烘焙"],
        nearbySpots: ["日泰寺參道","覺王山站","揚輝莊"],
        shoppingSideQuests: [{"name":"覺王山商店街雜貨店","category":"雜貨/甜點","description":"適合找小物、伴手禮與甜點。"}],
      },
      {
        id: 'd3-2',
        time: '10:30',
        title: '日泰寺',
        description: '從覺王山商店街步行前往日泰寺，參拜後再回商店街午餐或咖啡。',
        address_jp: '愛知県名古屋市千種区法王町1丁目1',
        address_en: '1-1 Hooucho, Chikusa-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1697, lng: 136.9546 },
        transportType: TransportType.WALK,
        transportDetail: '覺王山站/商店街步行前往',
        googleMapsQuery: 'Nittaiji Temple Nagoya',
        recommendedFood: ["參道和菓子","咖啡","糰子"],
        nearbySpots: ["覺王山商店街","揚輝莊"],
        shoppingSideQuests: [{"name":"日泰寺參道小店","category":"小吃/雜貨","description":"參拜前後可沿參道慢逛。"}],
      },
      {
        id: 'd3-3',
        time: '12:00',
        title: '覺王山午餐/咖啡',
        description: '在覺王山商店街用午餐或咖啡甜點，下午再移動到大須。',
        address_jp: '愛知県名古屋市千種区覚王山通',
        address_en: 'Kakuozan-dori, Chikusa-ku, Nagoya',
        coordinates: { lat: 35.166, lng: 136.952 },
        transportType: TransportType.WALK,
        transportDetail: '日泰寺步行返回覺王山商店街',
        googleMapsQuery: 'Kakuozan Cafe Nagoya',
        recommendedFood: ["咖啡","甜點","和菓子","輕食午餐"],
        nearbySpots: ["覺王山站","日泰寺","揚輝莊"],
        shoppingSideQuests: [{"name":"覺王山甜點店","category":"甜點","description":"適合安排一間咖啡店休息，不建議趕路。"}],
      },
      {
        id: 'd3-4',
        time: '13:30',
        title: '大須觀音',
        description: '從覺王山回到伏見轉鶴舞線，到大須觀音站。先參拜大須觀音，再進入大須商店街。',
        address_jp: '愛知県名古屋市中区大須2丁目21-47',
        address_en: '2-21-47 Osu, Naka-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1596, lng: 136.9001 },
        transportType: TransportType.TRAIN,
        transportDetail: '覺王山站 → 伏見站轉鶴舞線 → 大須觀音站；出站步行',
        googleMapsQuery: 'Osu Kannon Nagoya',
        recommendedFood: ["大須炸物","章魚燒","可麗餅","炸雞"],
        nearbySpots: ["大須商店街","仁王門通","赤門通"],
        shoppingSideQuests: [{"name":"大須觀音通","category":"商店街","description":"從大須觀音進商店街最順，不容易迷路。"}],
      },
      {
        id: 'd3-5',
        time: '14:30',
        title: '大須商店街',
        description: '逛大須商店街，重點是古著、動漫、電器、雜貨與街頭小吃。建議一路往上前津方向走。',
        address_jp: '愛知県名古屋市中区大須3丁目',
        address_en: 'Osu 3-chome, Naka-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1586, lng: 136.9052 },
        transportType: TransportType.WALK,
        transportDetail: '大須觀音步行進入商店街，往萬松寺與上前津方向移動',
        googleMapsQuery: 'Osu Shopping Street Nagoya',
        recommendedFood: ["コンパル炸蝦三明治","唐揚","章魚燒","可麗餅","李さんの台湾名物屋台"],
        nearbySpots: ["萬松寺","赤門通","新天地通","上前津站"],
        shoppingSideQuests: [{"name":"大須古著店群","category":"古著/雜貨","description":"大須適合安排較長逛街時間，不建議只停留一小時。"}],
      },
      {
        id: 'd3-6',
        time: '16:00',
        title: '萬松寺',
        description: '大須商店街內的重要寺院，可作為大須散策中段休息點。',
        address_jp: '愛知県名古屋市中区大須3丁目29-12',
        address_en: '3-29-12 Osu, Naka-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1584, lng: 136.9067 },
        transportType: TransportType.WALK,
        transportDetail: '大須商店街步行',
        googleMapsQuery: 'Banshoji Temple Nagoya',
        recommendedFood: ["大須街邊小吃","抹茶甜點","炸物"],
        nearbySpots: ["大須商店街","赤門通","上前津站"],
        shoppingSideQuests: [{"name":"萬松寺周邊商店","category":"小吃/雜貨","description":"周邊小吃密集，適合邊逛邊吃。"}],
      },
      {
        id: 'd3-7',
        time: '18:00',
        title: '矢場町晚餐',
        description: '從大須步行到矢場町用餐，避免再搭車。可吃矢場とん味噌豬排或回榮百貨餐廳。',
        address_jp: '愛知県名古屋市中区大須3丁目6-18',
        address_en: '3-6-18 Osu, Naka-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1602, lng: 136.9068 },
        transportType: TransportType.WALK,
        transportDetail: '大須商店街步行至矢場町/榮南側',
        googleMapsQuery: 'Yabaton Yabacho Honten',
        recommendedFood: ["矢場とん味噌豬排","コンパル炸蝦三明治","榮百貨餐廳"],
        nearbySpots: ["矢場町","名古屋 PARCO","松坂屋名古屋店"],
        shoppingSideQuests: [{"name":"名古屋 PARCO","category":"購物/餐飲","description":"晚餐後可逛街，或作為雨天備案。"}],
      },
      {
        id: 'd3-8',
        time: '19:30',
        title: '榮區晚間備案：Domatsuri 或百貨逛街',
        description: '若 Day 2 沒看夠 Domatsuri，可回榮區續看演舞；若人潮太多，改逛百貨或地下街。',
        address_jp: '愛知県名古屋市中区栄3丁目',
        address_en: 'Sakae 3-chome, Naka-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1648, lng: 136.9085 },
        transportType: TransportType.WALK,
        transportDetail: '矢場町步行至榮/久屋大通公園',
        googleMapsQuery: 'Hisaya Odori Park Nagoya',
        recommendedFood: ["祭典攤位","手羽先","百貨甜點"],
        nearbySpots: ["久屋大通公園","榮商圈","Oasis 21"],
        shoppingSideQuests: [{"name":"榮地下街","category":"地下街","description":"雨天或人潮過多時的穩定備案。"}],
      },
    ],
  },
  {
    isoDate: '2026-08-30',
    date: '8/30（日）',
    dayTitle: 'Day 4',
    theme: '犬山城一日遊',
    focus: '犬山城、三光稻荷神社、城下町集中步行',
    items: [
      {
        id: 'd4-1',
        time: '08:30',
        title: '從伏見前往名鐵名古屋站',
        description: '先由飯店搭地下鐵到名古屋站，再轉名鐵前往犬山。犬山日不要用名古屋地下鐵一日券當主票。',
        address_jp: '愛知県名古屋市中村区名駅1丁目',
        address_en: 'Meieki 1-chome, Nakamura-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1707, lng: 136.884 },
        transportType: TransportType.TRAIN,
        transportDetail: '伏見站 → 名古屋站；步行轉名鐵名古屋站',
        googleMapsQuery: 'Meitetsu Nagoya Station',
        recommendedFood: ["車站咖啡","早餐麵包","便利商店飯糰"],
        nearbySpots: ["名古屋站","JR Gate Tower","名鐵百貨"],
        shoppingSideQuests: [{"name":"名鐵百貨","category":"百貨","description":"若提早到名古屋站，可買飲料或早餐。"}],
      },
      {
        id: 'd4-2',
        time: '09:10',
        title: '搭名鐵前往犬山',
        description: '從名鐵名古屋站搭名鐵犬山線至犬山站或犬山遊園站。抵達後步行往犬山城下町。',
        address_jp: '愛知県犬山市犬山富士見町',
        address_en: 'Inuyama Fujimicho, Inuyama, Aichi',
        coordinates: { lat: 35.3791, lng: 136.9457 },
        transportType: TransportType.TRAIN,
        transportDetail: '名鐵名古屋站 → 犬山站/犬山遊園站；約 30-40 分鐘級距，依車種而定',
        googleMapsQuery: 'Inuyama Station',
        recommendedFood: ["犬山城下町小吃","五平餅","牛串"],
        nearbySpots: ["犬山站","犬山城下町","木曾川"],
        shoppingSideQuests: [{"name":"犬山站周邊","category":"補給","description":"出站前可先確認回程列車與購買飲料。"}],
      },
      {
        id: 'd4-3',
        time: '10:15',
        title: '犬山城',
        description: '優先參觀犬山城，早到可避開城下町午後人潮。參觀天守與木曾川景觀。',
        address_jp: '愛知県犬山市犬山北古券65-2',
        address_en: '65-2 Kitakoken, Inuyama, Aichi',
        coordinates: { lat: 35.3883, lng: 136.9392 },
        transportType: TransportType.WALK,
        transportDetail: '犬山站或犬山遊園站步行至犬山城',
        googleMapsQuery: 'Inuyama Castle',
        recommendedFood: ["城下町五平餅","味噌田樂","飛驒牛握壽司"],
        nearbySpots: ["三光稻荷神社","針綱神社","木曾川"],
        shoppingSideQuests: [{"name":"犬山城紀念品店","category":"伴手禮","description":"可購買犬山城限定紀念品。"}],
      },
      {
        id: 'd4-4',
        time: '11:30',
        title: '三光稻荷神社與針綱神社',
        description: '犬山城旁的神社集中參拜，路線不需繞遠。三光稻荷神社以粉色愛心繪馬知名。',
        address_jp: '愛知県犬山市犬山北古券41-1',
        address_en: '41-1 Kitakoken, Inuyama, Aichi',
        coordinates: { lat: 35.3869, lng: 136.9395 },
        transportType: TransportType.WALK,
        transportDetail: '犬山城步行前往',
        googleMapsQuery: 'Sanko Inari Shrine Inuyama',
        recommendedFood: ["城下町小吃","糰子","霜淇淋"],
        nearbySpots: ["犬山城","針綱神社","城下町"],
        shoppingSideQuests: [{"name":"三光稻荷神社御守","category":"御守/紀念品","description":"可購買戀愛、金運相關御守。"}],
      },
      {
        id: 'd4-5',
        time: '12:30',
        title: '犬山城下町午餐與散策',
        description: '中午集中在犬山城下町吃小吃與午餐，下午繼續逛伴手禮與老街。',
        address_jp: '愛知県犬山市犬山東古券',
        address_en: 'Higashikoken, Inuyama, Aichi',
        coordinates: { lat: 35.3817, lng: 136.9442 },
        transportType: TransportType.WALK,
        transportDetail: '神社步行下山至犬山城下町',
        googleMapsQuery: 'Inuyama Jokamachi',
        recommendedFood: ["五平餅","飛驒牛握壽司","牛串","醬油糰子","味噌田樂"],
        nearbySpots: ["犬山城下町","犬山站","老街小店"],
        shoppingSideQuests: [{"name":"犬山城下町小吃街","category":"小吃/伴手禮","description":"犬山一日遊的主要餐飲區，建議保留足夠時間。"}],
      },
      {
        id: 'd4-6',
        time: '15:30',
        title: '木曾川河畔散步',
        description: '午後到木曾川河畔散步，看犬山城與河景。若天氣太熱，可縮短停留時間。',
        address_jp: '愛知県犬山市犬山北古券',
        address_en: 'Kitakoken, Inuyama, Aichi',
        coordinates: { lat: 35.3894, lng: 136.9391 },
        transportType: TransportType.WALK,
        transportDetail: '城下町步行至木曾川河畔',
        googleMapsQuery: 'Kiso River Inuyama',
        recommendedFood: ["霜淇淋","冰品","飲料"],
        nearbySpots: ["犬山城","犬山橋","木曾川"],
        shoppingSideQuests: [{"name":"河畔咖啡/小店","category":"休息","description":"夏季午後適合找咖啡或冰品休息。"}],
      },
      {
        id: 'd4-7',
        time: '17:00',
        title: '返回名古屋',
        description: '從犬山站搭名鐵回名鐵名古屋站，再轉地下鐵回伏見或直接去榮晚餐。',
        address_jp: '愛知県名古屋市中区栄1丁目5-21',
        address_en: '1-5-21 Sakae, Naka-ku, Nagoya, Aichi',
        coordinates: { lat: 35.16769, lng: 136.89651 },
        transportType: TransportType.TRAIN,
        transportDetail: '犬山站 → 名鐵名古屋站 → 地下鐵名古屋站 → 伏見站；步行至飯店',
        googleMapsQuery: 'Daiwa Roynet Hotel Nagoya Fushimi',
        recommendedFood: ["榮手羽先","名古屋車站餐廳","味噌煮込みうどん"],
        nearbySpots: ["伏見站","榮","名古屋站"],
        shoppingSideQuests: [{"name":"名古屋站地下街","category":"購物/餐飲","description":"回程可先在名古屋站吃晚餐或採買。"}],
      },
      {
        id: 'd4-8',
        time: '18:30',
        title: '榮或伏見晚餐',
        description: '犬山日步行量大，晚上建議在飯店附近或榮區用餐，不再排遠景點。',
        address_jp: '愛知県名古屋市中区栄',
        address_en: 'Sakae, Naka-ku, Nagoya',
        coordinates: { lat: 35.1686, lng: 136.9062 },
        transportType: TransportType.TRAIN,
        transportDetail: '伏見站 → 榮站或步行前往伏見周邊餐廳',
        googleMapsQuery: 'Sakae Nagoya restaurants',
        recommendedFood: ["世界の山ちゃん手羽先","山本屋味噌煮込みうどん","榮百貨餐廳"],
        nearbySpots: ["榮商圈","Oasis 21","久屋大通公園"],
        shoppingSideQuests: [{"name":"榮商圈","category":"購物","description":"晚餐後可短逛，不建議安排過長。"}],
      },
    ],
  },
  {
    isoDate: '2026-08-31',
    date: '8/31（一）',
    dayTitle: 'Day 5',
    theme: '熱田神宮、名古屋站採買、返程',
    focus: '上午神社參拜，中午鰻魚飯三吃，下午回機場',
    items: [
      {
        id: 'd5-1',
        time: '09:00',
        title: '飯店退房/寄放行李',
        description: '先完成退房，將行李寄放飯店或帶往名古屋站置物櫃。上午安排熱田神宮。',
        address_jp: '愛知県名古屋市中区栄1丁目5-21',
        address_en: '1-5-21 Sakae, Naka-ku, Nagoya, Aichi',
        coordinates: { lat: 35.16769, lng: 136.89651 },
        transportType: TransportType.WALK,
        transportDetail: '飯店內辦理退房與寄放行李',
        googleMapsQuery: 'Daiwa Roynet Hotel Nagoya Fushimi',
        recommendedFood: ["飯店附近早餐","便利商店咖啡","喫茶店早餐"],
        nearbySpots: ["伏見站","御園座"],
        shoppingSideQuests: [{"name":"伏見便利商店","category":"補給","description":"出發前補水、防曬與零食。"}],
      },
      {
        id: 'd5-2',
        time: '09:30',
        title: '前往熱田神宮',
        description: '從伏見搭地下鐵前往熱田神宮周邊，上午參拜較不炎熱。',
        address_jp: '愛知県名古屋市熱田区神宮1丁目1-1',
        address_en: '1-1-1 Jingu, Atsuta-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1272, lng: 136.9087 },
        transportType: TransportType.TRAIN,
        transportDetail: '伏見站 → 上前津/榮轉名城線 → 熱田神宮西站或熱田神宮傳馬町站；出站步行',
        googleMapsQuery: 'Atsuta Jingu Shrine',
        recommendedFood: ["宮きしめん","鰻魚飯三吃","神宮周邊和菓子"],
        nearbySpots: ["熱田神宮本宮","信長塀","清水社","草薙館"],
        shoppingSideQuests: [{"name":"熱田神宮御守授與所","category":"御守/紀念品","description":"可購買御守與神社紀念品。"}],
      },
      {
        id: 'd5-3',
        time: '11:30',
        title: 'あつた蓬莱軒 本店午餐',
        description: '安排名古屋名物ひつまぶし。若排隊太久，改吃宮きしめん或名古屋站餐廳。',
        address_jp: '愛知県名古屋市熱田区神戸町503',
        address_en: '503 Godocho, Atsuta-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1248, lng: 136.9107 },
        transportType: TransportType.WALK,
        transportDetail: '熱田神宮步行或短程移動前往',
        googleMapsQuery: 'Atsuta Horaiken Honten',
        recommendedFood: ["ひつまぶし","鰻魚飯三吃","鰻魚料理"],
        nearbySpots: ["熱田神宮","神宮前站","熱田神宮傳馬町站"],
        shoppingSideQuests: [{"name":"熱田周邊老店","category":"餐飲","description":"若蓬萊軒排隊過久，可改找周邊老店或回名古屋站用餐。"}],
      },
      {
        id: 'd5-4',
        time: '13:30',
        title: '返回伏見/名古屋站拿行李',
        description: '午餐後返回飯店或名古屋站拿行李，下午安排最後採買。',
        address_jp: '愛知県名古屋市中村区名駅1丁目',
        address_en: 'Meieki 1-chome, Nakamura-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1707, lng: 136.884 },
        transportType: TransportType.TRAIN,
        transportDetail: '熱田神宮周邊 → 地下鐵/名鐵回伏見或名古屋站',
        googleMapsQuery: 'Nagoya Station',
        recommendedFood: ["名古屋站甜點","車站便當","名古屋伴手禮"],
        nearbySpots: ["JR Gate Tower","KITTE 名古屋","高島屋"],
        shoppingSideQuests: [{"name":"JR 名古屋高島屋","category":"百貨/伴手禮","description":"最後採買首選，甜點、名古屋名物與藥妝都方便。"}],
      },
      {
        id: 'd5-5',
        time: '14:30',
        title: '名古屋站最後採買',
        description: '在名古屋站區集中採買，不再往其他區域移動，保留充足時間前往機場。',
        address_jp: '愛知県名古屋市中村区名駅1丁目1-4',
        address_en: '1-1-4 Meieki, Nakamura-ku, Nagoya, Aichi',
        coordinates: { lat: 35.1709, lng: 136.8815 },
        transportType: TransportType.WALK,
        transportDetail: '名古屋站內與周邊步行',
        googleMapsQuery: 'JR Nagoya Takashimaya',
        recommendedFood: ["赤福","名古屋蝦餅","ういろう","車站便當"],
        nearbySpots: ["JR Gate Tower","名鐵百貨","ESCA 地下街"],
        shoppingSideQuests: [{"name":"ESCA 地下街","category":"地下街/伴手禮","description":"名古屋站新幹線側，餐廳與伴手禮集中。"}],
      },
      {
        id: 'd5-6',
        time: '16:30',
        title: '搭名鐵前往中部國際機場',
        description: '建議 16:30 前後從名鐵名古屋站出發，預留報到、安檢與退稅時間。',
        address_jp: '愛知県常滑市セントレア1-1',
        address_en: '1-1 Centrair, Tokoname, Aichi',
        coordinates: { lat: 34.8584, lng: 136.8054 },
        transportType: TransportType.TRAIN,
        transportDetail: '名鐵名古屋站 → 中部國際機場站；可搭 μ-SKY 或特急',
        googleMapsQuery: 'Chubu Centrair International Airport',
        recommendedFood: ["機場餐廳","機場伴手禮","登機前輕食"],
        nearbySpots: ["Centrair 4F","Sky Deck","免稅店"],
        shoppingSideQuests: [{"name":"Centrair 免稅店","category":"免稅/伴手禮","description":"最後補買零食與伴手禮。"}],
      },
      {
        id: 'd5-7',
        time: '19:55',
        title: 'JX 839 起飛回台北',
        description: '從名古屋中部國際機場搭乘 Starlux Airlines JX 839 返回台北。',
        address_jp: '愛知県常滑市セントレア1-1',
        address_en: '1-1 Centrair, Tokoname, Aichi',
        coordinates: { lat: 34.8584, lng: 136.8054 },
        transportType: TransportType.FLIGHT,
        transportDetail: 'Starlux Airlines JX 839 NGO → TPE',
        googleMapsQuery: 'Chubu Centrair International Airport Terminal',
        recommendedFood: ["機上餐","機場咖啡"],
        nearbySpots: ["登機門","免稅店"],
        shoppingSideQuests: [{"name":"登機口商店","category":"機場商店","description":"通過安檢後如有時間可最後採買。"}],
      },
    ],
  },
];
